config/routes.rb
MilkaProjekt::Application.routes.draw do
  match 'users/new' => 'users#new', as: :usernew
  match 'users/edit' => 'users#edit'
  get   'users/view'
  get   'users/edit/:id' => 'users#edit', as: :useredit, id: /\d+/
  get   'users/del/:id' => 'users#del', as: :userdel, id: /\d+/

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :login, :pass
  validates :name, presence: true
  validates :login, presence: true
  validates :email, presence: true
  validates :pass, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user'
  def new
    u = User.new(name: request.POST["name"],
                email: request.POST["email"],
                login: request.POST["login"],
                 pass: request.POST["pass"])
    if u.save
      flash[:success] = "Profile created"
    else
      render 'new'
    end

  end

  def edit
    @user = User.where(id: params[:id])

  end

  def del
    if @d = User.find(params[:id]).destroy
      flash[:success] = "Profile deleted"
    else
      redirect_to @d
    end
    redirect_to '/users/view'
  end

  def view
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MilkaProjekt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MilkaProjekt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header" style="text-align: center">
  <h1>User configuration</h1>
</div>
<%= link_to "New user", usernew_path %>
<%= link_to "Users view", '/users/view' %>
<%= yield %>
<div class="footer" style="text-align: center">
    <h4>milka coop...</h4>
</div>
</body>
</html>

app/views/users/edit.html.erb
<h1>User :</h1>
<% puts @user.name %>
<%= form_tag("/users/edit") do %>
  <% @user.each { |u| %>
    <%= label_tag(u.name, "Name") %>
    <%= text_field_tag(:name, u.name) %>
    <br>
    <%= label_tag(u.email, "E-mail") %>
    <%= text_field_tag(:email, u.email) %>
    <br>
    <%= label_tag(u.login, "Login") %>
    <%= text_field_tag(:login, u.login) %>
    <br>
    <%= label_tag(:pass, "New-pass") %>
    <%= text_field_tag(:pass) %>
    <br>
    <%= submit_tag("Save") %>
  <% } %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "New user") %>
<h1>New user</h1>
<%= form_tag("/users/new") do %>

    <%= label_tag(:name, "Name") %>
    <%= text_field_tag(:name) %>
    <br>
    <%= label_tag(:email, "E-mail") %>
    <%= text_field_tag(:email) %>
    <br>
    <%= label_tag(:login, "Login") %>
    <%= text_field_tag(:login) %>
    <br>
    <%= label_tag(:pass, "Password") %>
    <%= text_field_tag(:pass) %>
    <br>
<%= submit_tag("Save") %>
<% end %>

app/views/users/view.html.erb
<h1>Users</h1>
<table>
<% @user.each { |users| %>
    <tr>
      <td>
        <%=  users.name %>
      </td>
      <td>
        <%=  users.email %>
      </td>
      <td>
        <%=  users.login %>
      </td>
      <td>
        <%= link_to "Edit", useredit_path(users.id) %>
      </td>
      <td>
        <%= link_to "Delete", userdel_path(users.id) %>
      </td>
    </tr>
<% } %>
</table>